import requests
import pandas as pd
import io
# funnction to get keys
from agent_parse import get_api_key

# 1. Create a dummy DataFrame
df = pd.DataFrame({"Vendor": ["Acme"], "Budget": [2500000.0]})

# 2. Convert it to a CSV string in memory
csv_buffer = io.StringIO()
# makes a  temp file  in  RAM
df.to_csv(csv_buffer, index=False)


# 3. Push to CKAN via API
ckan_url = "http://YOUR_DEPARTMENT_CKAN_SERVER/api/3/action/resource_create"
headers = {"Authorization": get_api_key("CKAN_KEY")} # Store this in a .env file!

payload = {
    "package_id": "your-target-dataset-id",
    "name": "Automated_Vendor_Extraction_Report",
    "description": "Cleaned dataset generated by AI workflow.",
    "format": "CSV"
}

files = {
    # grabs csv  text  out  of the ram
    'upload': ('data.csv', csv_buffer.getvalue())
}

# post  it to the server
response = requests.post(ckan_url, data=payload, headers=headers, files=files)